
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace
        tty: true

    playwright:
        image: mcr.microsoft.com/playwright/mcp
        tty: true
        command: ["--port", "8931"]
